name: Verification
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [nixos-build, nixos-wsl-build, home-build, home-wsl-build, vm-test-nixos, vm-test-wsl-mock, vm-test-home-manager, vm-test-ubuntu-portability]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Secret Scanning (Gitleaks)
        if: github.actor != 'nektos/act'
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: DeterminateSystems/nix-installer-action@v14
        with:
          extra-conf: "accept-flake-config = true"
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - uses: cachix/cachix-action@v15
        with:
          name: u3kkasha
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Flake Check & Build
        run: |
          nix flake check ./nix --impure
          nix build ./nix#${{ matrix.target }} --impure
